import Foundation

// MARK: - User conventions (约定层, optional sidecar)

/// Optional per-machine sidecar describing the user's cross-list methodology
/// (e.g. what the flag means to them, which list is their inbox).
///
/// This is intentionally NOT generated by `setup`: conventions are personal
/// to each user, so the repo never ships or collects anyone's methodology.
/// Agents may gather it in conversation and write it here; power users may
/// edit it directly. Ordinary users can skip it entirely — per-list purpose
/// lives in `NotesStore` (notes.json, produced by `setup --deep`).
///
/// This complements the per-list semantic notes (`NotesStore`): conventions
/// describe cross-list methodology, notes describe single lists.
struct ConventionsStore {
    let fileURL: URL

    /// Default: `~/.local/share/remindkit/conventions.md`. Override with
    /// `REMINDKIT_CONVENTIONS_FILE` (e.g. a path inside iCloud Drive to get
    /// cross-device sync for free).
    static func defaultURL() -> URL {
        if let env = ProcessInfo.processInfo.environment["REMINDKIT_CONVENTIONS_FILE"],
           !env.isEmpty {
            return URL(fileURLWithPath: env)
        }
        let home = FileManager.default.homeDirectoryForCurrentUser
        return home.appendingPathComponent(".local/share/remindkit/conventions.md")
    }

    func load() -> String? {
        try? String(contentsOf: fileURL, encoding: .utf8)
    }

    func save(_ markdown: String) throws {
        let dir = fileURL.deletingLastPathComponent()
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        try markdown.write(to: fileURL, atomically: true, encoding: .utf8)
    }
}
