import Foundation

// MARK: - User conventions (约定层)

/// The user's personal methodology for using Reminders — how the lists,
/// flags, and workflow fit together. Lives in a sidecar markdown file so it
/// is (a) readable by any agent through the skill, (b) independent of the
/// Apple data, and (c) regenerated by `remindkit setup`.
///
/// This complements the per-list semantic notes (`NotesStore`): conventions
/// describe cross-list methodology, notes describe single lists.
struct ConventionsStore {
    let fileURL: URL

    /// Default: `~/.local/share/remindkit/conventions.md`. Override with
    /// `REMINDKIT_CONVENTIONS_FILE` (e.g. a path inside iCloud Drive).
    static func defaultURL() -> URL {
        if let env = ProcessInfo.processInfo.environment["REMINDKIT_CONVENTIONS_FILE"],
           !env.isEmpty {
            return URL(fileURLWithPath: env)
        }
        let home = FileManager.default.homeDirectoryForCurrentUser
        return home.appendingPathComponent(".local/share/remindkit/conventions.md")
    }

    func load() -> String? {
        try? String(contentsOf: fileURL, encoding: .utf8)
    }

    func save(_ markdown: String) throws {
        let dir = fileURL.deletingLastPathComponent()
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        try markdown.write(to: fileURL, atomically: true, encoding: .utf8)
    }
}

/// Answers collected by the interactive setup walkthrough.
struct SetupAnswers {
    var inboxList: String = "收集"                       // GTD 收集列表
    var inboxPurpose: String = "GTD 第一步「收集 inbox」：新想法/杂事先放这里，稍后分类"
    var okrList: String = "OKR"
    var okrPurpose: String = "OKR 方法论，规划未来一段时间的长期目标（季度/年度）"
    var flagMeaning: String = "当前关注的短期任务"
    var defaultList: String = "收集"                     // 新建提醒默认列表
    var extra: [String] = []                             // 其它自由约定
}

/// Render answers as the conventions markdown file.
func renderConventions(_ a: SetupAnswers, generatedAt: Date = Date()) -> String {
    let date = ISO8601DateFormatter().string(from: generatedAt)
    var md = """
    # remindkit 用户约定（user conventions）

    > 由 `remindkit setup` 生成于 \(date)。agent 处理提醒事项前先读本文件；
    > 用 `remindkit setup` 可重新生成。

    ## 方法论列表

    - **\(a.inboxList)**: \(a.inboxPurpose)
    - **\(a.okrList)**: \(a.okrPurpose)

    ## 旗标（flagged）含义

    \(a.flagMeaning)

    ## 新建提醒默认列表

    \(a.defaultList)

    """
    if !a.extra.isEmpty {
        md += "\n## 其它约定\n\n"
        for line in a.extra {
            md += "- \(line)\n"
        }
    }
    return md
}
